# Generated by Django 5.2.8 on 2025-11-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_termino', models.DateTimeField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appBiblioteca.salas')),
            ],
        ),
    ]
