# Generated by Django 5.2.8 on 2025-11-18 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
