# Generated by Django 5.2.8 on 2025-11-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblioteca', '0002_reserva_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='last_update',
        ),
    ]
